const XS_DEVICES_WIDTH = "480px";
const S_DEVICES_WIDTH = "768px";
const M_DEVICES_WIDTH = "1024px";
const L_DEVICES_WIDTH = "1366px";

export { XS_DEVICES_WIDTH, S_DEVICES_WIDTH, M_DEVICES_WIDTH, L_DEVICES_WIDTH };
