const XS_DEVICES_WIDTH = 480;
const S_DEVICES_WIDTH = 768;
const M_DEVICES_WIDTH = 1024;
const L_DEVICES_WIDTH = 1366;

export { XS_DEVICES_WIDTH, S_DEVICES_WIDTH, M_DEVICES_WIDTH, L_DEVICES_WIDTH };
